site_name: Персональный сайт Казара Владимира Сергеевича
site_description: Персональный сайт в рамках курсовой работы по дисциплине «Введение в веб технологии»
site_author: Казар Владимир Сергеевич
site_url: ""

theme:
  name: material
  language: ru
  logo: images/logo.svg
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
  palette:
    primary: teal
    accent: amber

plugins:
  - search

markdown_extensions:
  - admonition
  - tables
  - attr_list
  - md_in_html

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/SENATOROVAI
    - icon: fontawesome/brands/telegram
      link: https://t.me/KazarVladimir

copyright: Copyright © 2026 Казар Владимир Сергеевич

nav:
  - Главная: index.md
  - О себе: about.md
  - Опыт: projects.md
  - Контакты: contacts.md
  - Резюме: resume.md
  - Достижения: achievements.md
